### ISSUE TITLE
Get error then start s3a on Windows

### ISSUE THREAD

**Issue by vshumilov** [MrYsLab/s3-extend#32]
Hello,

Windows 10 (20H2, 19042.1237)
python 3.10.0
pip 21.2.4 from C:\Users\vvs\AppData\Roaming\Python\Python310\site-packages\pip (python 3.10)

I've try to start s3a.exe and get an error:
`PS C:\Users\vvs> C:\Users\vvs\AppData\Roaming\Python\Python310\Scripts\s3a.exe -c com6
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\vvs\AppData\Roaming\Python\Python310\Scripts\s3a.exe\__main__.py", line 7, in <module>
  File "C:\Users\vvs\AppData\Roaming\Python\Python310\site-packages\s3_extend\s3a.py", line 242, in s3ax
    S3A(com_port=com_port, arduino_instance_id=args.arduino_instance_id)
  File "C:\Users\vvs\AppData\Roaming\Python\Python310\site-packages\s3_extend\s3a.py", line 57, in __init__
    self.proc_bp = self.start_backplane()
  File "C:\Users\vvs\AppData\Roaming\Python\Python310\site-packages\s3_extend\s3a.py", line 172, in start_backplane
    return subprocess.Popen(['backplane'],
  File "C:\Program Files\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Не удается найти указанный файл
Exception ignored in atexit callback: <bound method S3A.killall of <s3_extend.s3a.S3A object at 0x000001D85D00FF10>>
Traceback (most recent call last):
  File "C:\Users\vvs\AppData\Roaming\Python\Python310\site-packages\s3_extend\s3a.py", line 153, in killall
    sys.exit(0)
SystemExit: 0

PS C:\Users\vvs> C:\Users\vvs\AppData\Roaming\Python\Python310\Scripts\s3a.exe
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\vvs\AppData\Roaming\Python\Python310\Scripts\s3a.exe\__main__.py", line 7, in <module>
  File "C:\Users\vvs\AppData\Roaming\Python\Python310\site-packages\s3_extend\s3a.py", line 242, in s3ax
    S3A(com_port=com_port, arduino_instance_id=args.arduino_instance_id)
  File "C:\Users\vvs\AppData\Roaming\Python\Python310\site-packages\s3_extend\s3a.py", line 57, in __init__
    self.proc_bp = self.start_backplane()
  File "C:\Users\vvs\AppData\Roaming\Python\Python310\site-packages\s3_extend\s3a.py", line 172, in start_backplane
    return subprocess.Popen(['backplane'],
  File "C:\Program Files\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Не удается найти указанный файл
Exception ignored in atexit callback: <bound method S3A.killall of <s3_extend.s3a.S3A object at 0x000001F39C53FF10>>
Traceback (most recent call last):
  File "C:\Users\vvs\AppData\Roaming\Python\Python310\site-packages\s3_extend\s3a.py", line 153, in killall
    sys.exit(0)
SystemExit: 0
PS C:\Users\vvs>`

1st step to diag:
`PS C:\Users\vvs> C:\Users\vvs\AppData\Roaming\Python\Python310\Scripts\backplane.exe

******************************************
Backplane IP address: 192.168.1.162
Subscriber Port = 43125
Publisher  Port = 43124
Loop Time = 0.001 seconds
******************************************
`

2nd step to diag:
`PS C:\Users\vvs> C:\Users\vvs\AppData\Roaming\Python\Python310\Scripts\ardgw.exe

Pymata Express Version 1.21
Copyright (c) 2018-2020 Alan Yorinks All rights reserved.

Opening all potential serial ports...
        COM6

Waiting 4 seconds(arduino_wait) for Arduino devices to reset...

Searching for an Arduino configured with an arduino_instance =  1

Arduino found and connected to COM6

Arduino Firmware ID: 1.2 FirmataExpress.ino
Auto-discovery complete. Found 20 Digital Pins and 6 Analog Pins

************************************************************
ArduinoGateway using Back Plane IP address: 192.168.1.162
Subscriber Port = 43125
Publisher  Port = 43124
************************************************************
`

3d step to diag:
`PS C:\Users\vvs> C:\Users\vvs\AppData\Roaming\Python\Python310\Scripts\wsgw.exe

************************************************************
WebSocket Gateway using Back Plane IP address: 192.168.1.162
Subscriber Port = 43125
Publisher  Port = 43124
************************************************************
WebSocket using: 192.168.1.162:9000
`

So, I don't know why s3a.exe not working.
How I can this start?

**Comment by vshumilov** [comment]
As well as python libs installed:

PS C:\Users\vvs> pip install s3-extend
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: s3-extend in c:\users\vvs\appdata\roaming\python\python310\site-packages (1.17)
Requirement already satisfied: pymata-rh in c:\users\vvs\appdata\roaming\python\python310\site-packages (from s3-extend) (1.2)
Requirement already satisfied: telemetrix-aio in c:\users\vvs\appdata\roaming\python\python310\site-packages (from s3-extend) (1.7)
Requirement already satisfied: python-banyan>=3.9 in c:\users\vvs\appdata\roaming\python\python310\site-packages (from s3-extend) (3.9)
Requirement already satisfied: pymata-express>=1.11 in c:\users\vvs\appdata\roaming\python\python310\site-packages (from s3-extend) (1.21)
Requirement already satisfied: pymata-cpx in c:\users\vvs\appdata\roaming\python\python310\site-packages (from s3-extend) (1.0)
Requirement already satisfied: tmx-pico-aio in c:\users\vvs\appdata\roaming\python\python310\site-packages (from s3-extend) (1.1)
Requirement already satisfied: pyserial in c:\users\vvs\appdata\roaming\python\python310\site-packages (from pymata-express>=1.11->s3-extend) (3.5)
Requirement already satisfied: msgpack-numpy in c:\users\vvs\appdata\roaming\python\python310\site-packages (from python-banyan>=3.9->s3-extend) (0.4.7.1)
Requirement already satisfied: apscheduler in c:\users\vvs\appdata\roaming\python\python310\site-packages (from python-banyan>=3.9->s3-extend) (3.8.0)
Requirement already satisfied: websockets in c:\users\vvs\appdata\roaming\python\python310\site-packages (from python-banyan>=3.9->s3-extend) (10.0)
Requirement already satisfied: psutil in c:\users\vvs\appdata\roaming\python\python310\site-packages (from python-banyan>=3.9->s3-extend) (5.8.0)
Requirement already satisfied: pyzmq in c:\users\vvs\appdata\roaming\python\python310\site-packages (from python-banyan>=3.9->s3-extend) (22.3.0)
Requirement already satisfied: numpy>=1.9 in c:\users\vvs\appdata\roaming\python\python310\site-packages (from python-banyan>=3.9->s3-extend) (1.21.2+mkl)
Requirement already satisfied: msgpack-python in c:\users\vvs\appdata\roaming\python\python310\site-packages (from python-banyan>=3.9->s3-extend) (0.5.6)
Requirement already satisfied: pytz in c:\users\vvs\appdata\roaming\python\python310\site-packages (from apscheduler->python-banyan>=3.9->s3-extend) (2021.3)
Requirement already satisfied: setuptools>=0.7 in c:\program files\python310\lib\site-packages (from apscheduler->python-banyan>=3.9->s3-extend) (57.4.0)
Requirement already satisfied: tzlocal~=2.0 in c:\users\vvs\appdata\roaming\python\python310\site-packages (from apscheduler->python-banyan>=3.9->s3-extend) (2.1)
Requirement already satisfied: six>=1.4.0 in c:\users\vvs\appdata\roaming\python\python310\site-packages (from apscheduler->python-banyan>=3.9->s3-extend) (1.16.0)
Requirement already satisfied: msgpack>=0.5.2 in c:\users\vvs\appdata\roaming\python\python310\site-packages (from msgpack-numpy->python-banyan>=3.9->s3-extend) (1.0.2)
PS C:\Users\vvs>
