### ISSUE TITLE
Cannot start espgw/wsgw on Windows 7 64-bit

### ISSUE THREAD

**Issue by Anton-V-K** [MrYsLab/s3-extend#34]
I'm unable to start `espgw` or `wsgw` on Windows 7 SP1 64-bit with Python 3.8.6 32-bit; `backplane` starts fine.
```
E:\Users\Anton>espgw
TelemetrixAIO Version: 1.7
Copyright (c) 2018-2020 Alan Yorinks All rights reserved.

Traceback (most recent call last):
  File "c:\program files (x86)\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files (x86)\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python38-32\Scripts\espgw.exe\__main__.py", line 7, in <module>
  File "c:\program files (x86)\python38-32\lib\site-packages\s3_extend\gateways\esp8266_gateway.py", line 392, in esp8266_gateway
    app = Esp8266Gateway(subscriber_list, **kw_options, event_loop=loop)
  File "c:\program files (x86)\python38-32\lib\site-packages\s3_extend\gateways\esp8266_gateway.py", line 73, in __init__
    super(Esp8266Gateway, self).__init__(subscriber_list=subscriber_list,
  File "c:\program files (x86)\python38-32\lib\site-packages\python_banyan\gateway_base_aio\gateway_base_aio.py", line 113, in __init__
    super(GatewayBaseAIO, self).__init__(back_plane_ip_address=back_plane_ip_address,
  File "c:\program files (x86)\python38-32\lib\site-packages\python_banyan\banyan_base_aio\banyan_base_aio.py", line 116, in __init__
    p = psutil.Process(pid)
  File "c:\program files (x86)\python38-32\lib\site-packages\psutil\__init__.py", line 326, in __init__
    self._init(pid)
  File "c:\program files (x86)\python38-32\lib\site-packages\psutil\__init__.py", line 354, in _init
    self.create_time()
  File "c:\program files (x86)\python38-32\lib\site-packages\psutil\__init__.py", line 710, in create_time
    self._create_time = self._proc.create_time()
  File "c:\program files (x86)\python38-32\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
  File "c:\program files (x86)\python38-32\lib\site-packages\psutil\_pswindows.py", line 671, in convert_oserror
    raise exc
  File "c:\program files (x86)\python38-32\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "c:\program files (x86)\python38-32\lib\site-packages\psutil\_pswindows.py", line 933, in create_time
    user, system, created = cext.proc_times(self.pid)
OSError: [WinError 0] Операция успешно завершена: '(originated from OpenProcess)'
```
```
E:\Users\Anton>wsgw -i 9002
Traceback (most recent call last):
  File "c:\program files (x86)\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files (x86)\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python38-32\Scripts\wsgw.exe\__main__.py", line 7, in <module>
  File "c:\program files (x86)\python38-32\lib\site-packages\s3_extend\gateways\ws_gateway.py", line 282, in ws_gateway
    WsGateway(subscription_list, **kw_options, event_loop=loop)
  File "c:\program files (x86)\python38-32\lib\site-packages\s3_extend\gateways\ws_gateway.py", line 79, in __init__
    super(WsGateway, self).__init__(subscriber_list=subscription_list,
  File "c:\program files (x86)\python38-32\lib\site-packages\python_banyan\banyan_base_aio\banyan_base_aio.py", line 116, in __init__
    p = psutil.Process(pid)
  File "c:\program files (x86)\python38-32\lib\site-packages\psutil\__init__.py", line 326, in __init__
    self._init(pid)
  File "c:\program files (x86)\python38-32\lib\site-packages\psutil\__init__.py", line 354, in _init
    self.create_time()
  File "c:\program files (x86)\python38-32\lib\site-packages\psutil\__init__.py", line 710, in create_time
    self._create_time = self._proc.create_time()
  File "c:\program files (x86)\python38-32\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
  File "c:\program files (x86)\python38-32\lib\site-packages\psutil\_pswindows.py", line 671, in convert_oserror
    raise exc
  File "c:\program files (x86)\python38-32\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "c:\program files (x86)\python38-32\lib\site-packages\psutil\_pswindows.py", line 933, in create_time
    user, system, created = cext.proc_times(self.pid)
OSError: [WinError 0] Операция успешно завершена: '(originated from OpenProcess)'
```
```
Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:37:30) [MSC v.1927 32 bit (Intel)] on win32
```

**Comment by Anton-V-K** [comment]
Too bad you aren't going to support Windows 7, which is an optimal choice for an educational box on an old piece of hardware.
